apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - args: ["-m", "prometheus", "all"]
          image: jaegertracing/example-hotrod:latest
          name: hotrod
          ports:
            - name: frontend
              containerPort: 8080
            - name: customer
              containerPort: 8081
            - name: driver
              containerPort: 8082
            - name: route
              containerPort: 8083
